import './globals.css'
import { Play } from 'next/font/google'

const inter = Play({
  subsets: ['latin'],
  weight: '400'
})

export const metadata = {
  title: 'Gay Lussac\'s Law',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        {children}
      </body>
    </html>
  )
}
